Dntglk_Fish = {
	FishSet = {
		Fish = {
			{
				VisualID = 1,
				Name = "小黄鱼",
				BroadCast = "false",
				TypeID = 1,
				BoundingBox = 1,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 500,
				Speed = 150,
				LockLevel = 0,
				Particle = ""
			},
			{
				VisualID = 2,
				Name = "绿草鱼",
				BroadCast = "false",
				TypeID = 2,
				BoundingBox = 2,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 500,
				Speed = 139,
				LockLevel = 0,
				Particle = ""
			},
			{
				VisualID = 3,
				Name = "黄草鱼",
				BroadCast = "false",
				TypeID = 3,
				BoundingBox = 3,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 333,
				Speed = 142,
				LockLevel = 0,
				Particle = ""
			},
			{
				VisualID = 4,
				Name = "大眼鱼",
				BroadCast = "false",
				TypeID = 4,
				BoundingBox = 4,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 250,
				Speed = 128,
				LockLevel = 0,
				Particle = "bubble"
			},
			{
				VisualID = 5,
				Name = "黄边鱼",
				BroadCast = "false",
				TypeID = 5,
				BoundingBox = 5,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 200,
				Speed = 148,
				LockLevel = 0,
				Particle = "bubble"
			},
			{
				VisualID = 6,
				Name = "小丑鱼",
				BroadCast = "false",
				TypeID = 6,
				BoundingBox = 6,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 166,
				Speed = 149,
				LockLevel = 0,
				Particle = "bubble"
			},
			{
				VisualID = 7,
				Name = "小刺鱼",
				BroadCast = "false",
				TypeID = 7,
				BoundingBox = 7,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 142,
				Speed = 160,
				LockLevel = 0,
				Particle = "switch"
			},
			{
				VisualID = 8,
				Name = "蓝鱼",
				BroadCast = "false",
				TypeID = 8,
				BoundingBox = 8,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 125,
				Speed = 151,
				LockLevel = 0,
				Particle = "switch"
			},
			{
				VisualID = 9,
				Name = "灯笼鱼",
				BroadCast = "false",
				TypeID = 9,
				BoundingBox = 9,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 111,
				Speed = 170,
				LockLevel = 0,
				Particle = "bubble"
			},
			{
				VisualID = 10,
				Name = "海龟",
				BroadCast = "false",
				TypeID = 10,
				BoundingBox = 10,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 100,
				Speed = 122,
				LockLevel = 0,
				Particle = "switch"
			},
			{
				VisualID = 11,
				Name = "花斑鱼",
				BroadCast = "false",
				TypeID = 11,
				BoundingBox = 11,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 83,
				Speed = 163,
				LockLevel = 0,
				Particle = "bubble"
			},
			{
				VisualID = 12,
				Name = "蝴蝶鱼",
				BroadCast = "false",
				TypeID = 12,
				BoundingBox = 12,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 66,
				Speed = 143,
				LockLevel = 0,
				Particle = "bubble"
			},
			{
				VisualID = 13,
				Name = "孔雀鱼",
				BroadCast = "false",
				TypeID = 13,
				BoundingBox = 13,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 55,
				Speed = 153,
				LockLevel = 0,
				Particle = "bubble"
			},
			{
				VisualID = 14,
				Name = "剑鱼",
				BroadCast = "false",
				TypeID = 14,
				BoundingBox = 14,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 50,
				Speed = 177,
				LockLevel = 0,
				Particle = "bubble"
			},
			{
				VisualID = 15,
				Name = "蝙蝠鱼",
				BroadCast = "false",
				TypeID = 15,
				BoundingBox = 15,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 40,
				Speed = 131,
				LockLevel = 0,
				Particle = "salute1"
			},
			{
				VisualID = 16,
				Name = "银鲨",
				BroadCast = "false",
				TypeID = 16,
				BoundingBox = 16,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 33,
				Speed = 183,
				LockLevel = 1,
				Particle = "salute1"
			},
			{
				VisualID = 17,
				Name = "金鲨",
				BroadCast = "false",
				TypeID = 17,
				BoundingBox = 17,
				ShowBingo = "false",
				ShakeScreen = "false",
				Probability = 28.5,
				Speed = 195,
				LockLevel = 1,
				Particle = "salute1"
			},
			{
				VisualID = 18,
				Name = "小海豚",
				BroadCast = "false",
				TypeID = 18,
				BoundingBox = 18,
				ShowBingo = "true",
				ShakeScreen = "true",
				Probability = 25,
				Speed = 66,
				LockLevel = 2,
				Particle = "salute1"
			},
			{
				VisualID = 19,
				Name = "霸王鲸",
				BroadCast = "true",
				TypeID = 19,
				BoundingBox = 19,
				ShowBingo = "true",
				ShakeScreen = "true",
				Probability = 20,
				Speed = 128,
				LockLevel = 3,
				Particle = "salute1"
			},
			[21] = {
				VisualID = 21,
				Name = "银龙",
				BroadCast = "true",
				TypeID = 21,
				BoundingBox = 21,
				ShowBingo = "true",
				ShakeScreen = "true",
				Probability = 12,
				Speed = 176,
				LockLevel = 4,
				Particle = "salute1"
			},
			[22] = {
				VisualID = 22,
				Name = "金龙",
				BroadCast = "true",
				TypeID = 22,
				BoundingBox = 22,
				ShowBingo = "true",
				ShakeScreen = "true",
				Probability = 10,
				UseMultiPointsLocking = "true",
				Speed = 180,
				LockLevel = 4,
				Particle = "salute1"
			},
			[23] = {
				VisualID = 23,
				Name = "章鱼王",
				BroadCast = "true",
				TypeID = 23,
				BoundingBox = 23,
				ShowBingo = "true",
				ShakeScreen = "true",
				Probability = 7,
				Speed = 59,
				LockLevel = 4,
				Particle = "bomb"
			},
			[24] = {
				VisualID = 24,
				Name = "海妖",
				BroadCast = "true",
				TypeID = 24,
				BoundingBox = 24,
				ShowBingo = "true",
				ShakeScreen = "true",
				Probability = 10,
				Speed = 66,
				LockLevel = 4,
				Particle = "bomb"
			},
			[25] = {
				VisualID = 25,
				Name = "神仙船",
				BroadCast = "true",
				TypeID = 25,
				BoundingBox = 25,
				ShowBingo = "true",
				ShakeScreen = "true",
				Probability = 10,
				Speed = 42,
				LockLevel = 4,
				Particle = "bomb"
			},
			[27] = {
				IsBoss = true,
				Name = "双头企鹅",
				BroadCast = "true",
				TypeID = 27,
				BoundingBox = 27,
				ShowBingo = "true",
				ShakeScreen = "true",
				VisualID = 27,
				Probability = 3.3,
				IdleDuration = 6.533333333333333,
				Speed = 76,
				LockLevel = 8,
				Particle = "bomb",
				StopTime = {
					10,
					30
				}
			},
			[29] = {
				IsBoss = true,
				Name = "李逵",
				BroadCast = "true",
				TypeID = 29,
				BoundingBox = 29,
				ShowBingo = "true",
				ShakeScreen = "true",
				VisualID = 29,
				Probability = 3.3,
				IdleDuration = 6.533333333333333,
				Speed = 123,
				LockLevel = 5,
				Particle = "bomb",
				StopTime = {
					10,
					30
				}
			},
			[300] = {
				VisualID = 300,
				Name = "大四喜",
				BroadCast = "true",
				TypeID = 300,
				BoundingBox = 300,
				ShowBingo = "true",
				ShakeScreen = "false",
				EffectType = 1,
				Probability = 20,
				Speed = 78,
				LockLevel = 5,
				Particle = "bomb"
			},
			[301] = {
				VisualID = 301,
				Name = "大四喜",
				BroadCast = "true",
				TypeID = 301,
				BoundingBox = 300,
				ShowBingo = "true",
				ShakeScreen = "false",
				EffectType = 1,
				Probability = 20,
				Speed = 78,
				LockLevel = 5,
				Particle = "bomb"
			},
			[302] = {
				VisualID = 302,
				Name = "大四喜",
				BroadCast = "true",
				TypeID = 302,
				BoundingBox = 300,
				ShowBingo = "true",
				ShakeScreen = "false",
				EffectType = 1,
				Probability = 20,
				Speed = 78,
				LockLevel = 5,
				Particle = "bomb"
			},
			[303] = {
				VisualID = 303,
				Name = "大四喜",
				BroadCast = "true",
				TypeID = 303,
				BoundingBox = 300,
				ShowBingo = "true",
				ShakeScreen = "false",
				EffectType = 1,
				Probability = 20,
				Speed = 78,
				LockLevel = 5,
				Particle = "bomb"
			},
			[304] = {
				VisualID = 304,
				Name = "大四喜",
				BroadCast = "true",
				TypeID = 304,
				BoundingBox = 300,
				ShowBingo = "true",
				ShakeScreen = "false",
				EffectType = 1,
				Probability = 20,
				Speed = 78,
				LockLevel = 5,
				Particle = "bomb"
			},
			[500] = {
				VisualID = 500,
				Name = "万佛朝宗",
				BroadCast = "true",
				TypeID = 500,
				BoundingBox = 500,
				ShowBingo = "true",
				ShakeScreen = "true",
				EffectType = 2,
				Probability = 0.1,
				Speed = 119,
				LockLevel = 4,
				Particle = "bomb"
			},
			[501] = {
				VisualID = 1002,
				Name = "金箍棒",
				BroadCast = "true",
				TypeID = 501,
				BoundingBox = 501,
				ShowBingo = "true",
				ShakeScreen = "true",
				Probability = 0.1,
				Speed = 117,
				LockLevel = 4,
				Particle = "bomb"
			},
			[502] = {
				VisualID = 1003,
				Name = "定屏炸弹",
				BroadCast = "false",
				TypeID = 502,
				BoundingBox = 502,
				ShowBingo = "false",
				ShakeScreen = "true",
				Probability = 50,
				Speed = 116,
				LockLevel = 4,
				Particle = ""
			},
			[801] = {
				VisualID = 801,
				Name = "大三元",
				BroadCast = "true",
				TypeID = 801,
				BoundingBox = 800,
				ShowBingo = "true",
				ShakeScreen = "false",
				EffectType = 1,
				Probability = 20,
				Speed = 46,
				LockLevel = 5,
				Particle = "bomb"
			},
			[802] = {
				VisualID = 802,
				Name = "大三元",
				BroadCast = "true",
				TypeID = 802,
				BoundingBox = 800,
				ShowBingo = "true",
				ShakeScreen = "false",
				EffectType = 1,
				Probability = 20,
				Speed = 46,
				LockLevel = 5,
				Particle = "bomb"
			},
			[803] = {
				VisualID = 803,
				Name = "大三元",
				BroadCast = "true",
				TypeID = 803,
				BoundingBox = 800,
				ShowBingo = "true",
				ShakeScreen = "false",
				EffectType = 1,
				Probability = 20,
				Speed = 46,
				LockLevel = 5,
				Particle = "bomb"
			},
			[804] = {
				VisualID = 804,
				Name = "大三元",
				BroadCast = "true",
				TypeID = 804,
				BoundingBox = 800,
				ShowBingo = "true",
				ShakeScreen = "false",
				EffectType = 1,
				Probability = 20,
				Speed = 46,
				LockLevel = 5,
				Particle = "bomb"
			},
			[805] = {
				VisualID = 805,
				Name = "大三元",
				BroadCast = "true",
				TypeID = 805,
				BoundingBox = 800,
				ShowBingo = "true",
				ShakeScreen = "false",
				EffectType = 1,
				Probability = 20,
				Speed = 46,
				LockLevel = 5,
				Particle = "bomb"
			}
		}
	}
}

return
